#ifndef GAMECONSTS_HPP_INCLUDED
#define GAMECONSTS_HPP_INCLUDED

#define STARTING_PLAYER_NUMBER 1
#define MAX_CONNECTIONS 2
#define DEFAULT_TURN_TIME 30
#define SERVER_PORT 2137

#endif // GAMECONSTS_HPP_INCLUDED
